### ISSUE TITLE
Critical bug in SendMoneyCommand

### ISSUE THREAD

**Issue by BurakDmb** [PipesPotatoes/Economy#1]
Hi,

Firstly, I would like to say good luck to you all for developing a modded minecraft server project.

If we come to the problem, when I'm reviewing the SendMoneyCommand, I think I found a critical bug.

In SendMoneyCommand.kt, the argument the player has entered has not been checked for negative values. It's just been checked if its enough or not. 
So if the player enters a negative value, he can recieves money from the other player as well.

Also its a good idea to check the corner cases too, because this is a very important command and there shouldn't be any bug in it.

https://github.com/PipesPotatoes/Economy/blob/5716856d303d6164115e8bf4678c5434ff6ad153/src/main/kotlin/command/SendMoneyCommand.kt#L19-L30

**Comment by Admicos** [comment]
Yeah, I didn't really think about much of it when I wrote that.

I'll try fixing it when we move Economy over to the PipesPotatoes/PipePotato plugin

**Comment by BurakDmb** [comment]
Also i saw there is an Economy API in SpongeAPI. You should check it out, maybe it can make your work easier in moving the economy over to your main plugin.

[https://docs.spongepowered.org/stable/en/plugin/economy/index.html](https://docs.spongepowered.org/stable/en/plugin/economy/index.html)

Other than that, I've nothing to add, I wish you good luck again :D

**Comment by Admicos** [comment]
Yeah, I tried using the economy API, but found it a little complicated to work with as an implementor. My eventual hope is I can make that work, but until then, hacky replacements it is.
